// Date is a Constructor
var date = new Date()
console.log(date.toDateString())
console.log(date.toTimeString())
console.log(date.toLocaleString())
console.log(date.toUTCString())
console.log(date.toString())
console.log(date.toLocaleTimeString())
console.log(date.toLocaleDateString())
console.log(date.toISOString())

console.log(date.getFullYear())
console.log(date.getMonth())
console.log(date.getDate())
console.log(date.getHours())
console.log(date.getMinutes())
console.log(date.getSeconds())